Site

title: "Cybersecurity Program" author: "Phantom" logo: _static/logo.png # optional

Execute notebooks on build (use 'off' if you prefer)

execute: execute_notebooks: auto timeout: 60

MyST & HTML behavior

parse: myst_enable_extensions: - colon_fence - deflist - tasklist - html_admonition

GitHub integration buttons

html: use_repository_button: true use_issues_button: true use_edit_page_button: true

Launch buttons (like your example)

launch_buttons: colab_url: "https://colab.research.google.com" notebook_interface: classic

Make the top-right download menu appear

sphinx: config: html_theme_options: use_download_button: true

Point to your repo so links work

repository: url: https://github.com/gatsbywelles/DeepFake-Detection-Learning-Modules/tree/main/book # ← update me path_to_book: book branch: main
