name: deploy-book


on:
# Manual-only to avoid emails on push
workflow_dispatch:


permissions:
contents: read
pages: write
id-token: write


concurrency:
group: pages
cancel-in-progress: true


jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Setup Python
uses: actions/setup-python@v5
with:
python-version: "3.11"


- name: Install dependencies
run: pip install jupyter-book


- name: Build Jupyter Book
run: jb build book/


- name: Upload artifact
uses: actions/upload-pages-artifact@v3
with:
path: book/_build/html


deploy:
needs: build
runs-on: ubuntu-latest
permissions:
pages: write
uses: actions/deploy-pages@v4
